"""Device contracts + the per-run trust ledger.

This module encodes the three single-shot-experiment disciplines as data, so the
trust ledger at the top of every ``report.md`` is generated by construction
rather than by remembering to check things by hand:

  1. **Known-answer calibration** — each device declares a fixture (here, the
     vacuum / ``A=0`` state) and a null-predicate that its output MUST satisfy
     when run on that fixture *in the same run*.  A device whose calibration
     fails this run does not get to vote on physics.  (The vacuum self-test also
     catches the prestressed-N-gon offset-subtraction bugs that LESSONS_LEARNED
     warns about: if a device forgets to subtract the offset, its vacuum output
     is non-null and calibration FAILS.)

  2. **Pre-registered falsifier** — each device declares, as a predicate living
     in *this* version-controlled file, what would count as a pass.  Moving a
     threshold to make a result pass shows up as a diff in the contract, not
     buried in the measurement: the "fixing the instrument vs. tuning to confirm"
     line made visible in git.

  3. **Layered, bottom-up analysis** — each device carries an emergence-layer
     rank.  The ledger sorts by layer and finds the first failing layer; every
     device above it is marked *uninterpretable* (it rests on a failed lower
     layer), so a human reads the run bottom-up and fixes the first ✗.

Falsifier predicates take ``(result, ctx)`` and return ``True`` (pass),
``False`` (fail), or ``None`` (untested — e.g. a physics check that is only
meaningful on a converged solved state, not on the seed).  ``ctx`` carries
``converged``, ``m``, ``n_t`` and a human-readable ``state`` string.

Design constraint (PRINCIPLES §2): read-only.  Nothing here mutates solver
state; calibration runs devices on a synthesized vacuum world into a throwaway
directory and inspects only their returned metric dicts.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Callable

import numpy as np

from branesim.initialization.vortex_worldtube import (
    CARRIER_RE,
    CARRIER_IM,
    vacuum_offsets,
)

# Tolerances (the version-controlled thresholds — move with intent, see the diff).
NULL_TOL: float = 1e-6        # |metric| below this on the vacuum fixture = null
ENERGY_NULL_TOL: float = 1e-8  # V_excess at the reference config
CONS_TOL: float = 1e-2        # energy-conservation max relative deviation
SPREAD_LOCALIZED: float = 1.0  # spread_ratio < this = localized (not box-filling)
U1_PURE_FRAC: float = 0.99    # pure-EM (trace) seed: U(1) energy fraction ≈ 1
BINDING_NOISE: float = 1e-3   # Δu_∥ extremum must exceed this to count as signal


# ---------------------------------------------------------------------------
# Contract dataclass + registry
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DeviceContract:
    """The three declarations that make a device's output trustworthy.

    Attributes
    ----------
    layer : int
        Emergence rank (1 substrate/linear → 5 soliton).  Lower layers must hold
        before higher-layer verdicts are interpretable.
    layer_name : str
        Human label for the layer.
    calib_fixture : {"vacuum", "none"}
        Which known-answer fixture calibrates this device.  ``"vacuum"`` runs the
        device on the ``A=0`` state and checks ``calib_check``.  ``"none"`` means
        no clean vacuum null exists yet (declared gap; shown as ``—``).
    calib_desc : str
        One-line description of the calibration.
    calib_check : callable(result_dict) -> bool | None
        Null-predicate on the device's output when run on the fixture.  ``None``
        iff ``calib_fixture == "none"``.
    falsifier_desc : str
        One-line description of the pre-registered pass criterion.
    falsifier : callable(result_dict, ctx) -> bool | None
        ``True`` pass / ``False`` fail / ``None`` untested-on-this-state.
    """

    layer: int
    layer_name: str
    calib_fixture: str
    calib_desc: str
    calib_check: Callable[[dict], bool] | None
    falsifier_desc: str
    falsifier: Callable[[dict, dict], bool | None]


def _num(d: dict, key: str, default: float = float("nan")) -> float:
    """Pull a numeric metric, tolerating missing/non-numeric entries."""
    v = d.get(key, default)
    try:
        return float(v)
    except (TypeError, ValueError):
        return float("nan")


CONTRACTS: dict[str, DeviceContract] = {
    # ---- Layer 1: substrate / linear consistency ----
    "energy": DeviceContract(
        layer=1, layer_name="L1 substrate",
        calib_fixture="vacuum",
        calib_desc="A=0 → V_excess ≡ 0 and vacuum_stable",
        # bool(...) not `is True`: device returns a numpy bool (np.True_).
        calib_check=lambda r: (bool(r.get("vacuum_stable"))
                               and abs(_num(r, "V_excess_mean", 1.0)) < ENERGY_NULL_TOL),
        falsifier_desc="E conserved over the loop (max rel. dev < 1e-2) — converged states only",
        falsifier=lambda r, c: (None if not c.get("converged")
                                else _num(r, "E_conservation_max_dev") < CONS_TOL),
    ),
    "spectra": DeviceContract(
        layer=1, layer_name="L1 substrate",
        calib_fixture="vacuum",
        calib_desc="A=0 → carrier power spectrum ≡ 0",
        calib_check=lambda r: _num(r, "total_power", 1.0) < NULL_TOL,
        falsifier_desc="radiation-tail threshold not yet pinned",
        falsifier=lambda r, c: None,
    ),
    # ---- Layer 2: gauge content (localization, U(1) charge, U(3) split) ----
    "confinement": DeviceContract(
        layer=2, layer_name="L2 gauge content",
        calib_fixture="none",
        calib_desc="no vacuum null (strain weight ≡0 on A=0 is degenerate)",
        calib_check=None,
        falsifier_desc="localized object: spread_ratio < 1 (not box-filling)",
        falsifier=lambda r, c: _num(r, "spread_ratio_mean") < SPREAD_LOCALIZED,
    ),
    "winding": DeviceContract(
        layer=2, layer_name="L2 gauge content",
        # Vacuum is degenerate: with |Ψ|≡0 the phase is atan2(noise,noise) and the
        # contour winding is meaningless.  The known-answer fixture is instead the
        # analytic m-vortex seed (winding_z=m), which the falsifier checks directly.
        calib_fixture="none",
        calib_desc="no vacuum null (phase undefined when |Ψ|≡0); calibrated by the m-seed via the falsifier",
        calib_check=None,
        falsifier_desc="winding_z ≈ m, off-axis ≈ 0, constant over the loop",
        falsifier=lambda r, c: r.get("winding_ok"),
    ),
    "color_channels": DeviceContract(
        layer=2, layer_name="L2 gauge content",
        calib_fixture="vacuum",
        calib_desc="A=0 → U(1) and SU(3) channel energies ≡ 0",
        calib_check=lambda r: (_num(r, "u1_energy_t0", 1.0) < NULL_TOL
                               and _num(r, "su3_energy_t0", 1.0) < NULL_TOL),
        falsifier_desc="pure-EM seed → U(1) fraction ≈ 1 (single-component ⅓ is NOT pure EM, E1)",
        falsifier=lambda r, c: _num(r, "u1_fraction_mean") > U1_PURE_FRAC,
    ),
    # ---- Layer 3: Berry connection / emergent EM ----
    "berry": DeviceContract(
        layer=3, layer_name="L3 Berry/EM",
        calib_fixture="vacuum",
        calib_desc="A=0 → carrier amplitude and Berry connection ≡ 0",
        calib_check=lambda r: (_num(r, "amp_max_t0", 1.0) < NULL_TOL
                               and abs(_num(r, "berry_connection_At_mean", 1.0)) < NULL_TOL),
        falsifier_desc="emergent carrier closure: Berry phase ≈ 2π·n_t — converged states only (E8)",
        falsifier=lambda r, c: (None if not c.get("converged")
                                else abs(_num(r, "berry_phase_accum_final")
                                         - 2.0 * math.pi * (c.get("n_t") or 0)) < 0.5),
    ),
    "em_fields": DeviceContract(
        layer=3, layer_name="L3 Berry/EM",
        calib_fixture="vacuum",
        calib_desc="A=0 → A_μ and B ≡ 0",
        calib_check=lambda r: (_num(r, "A_x_max", 1.0) < NULL_TOL
                               and _num(r, "A_y_max", 1.0) < NULL_TOL
                               and _num(r, "B_z_max_midplane", 1.0) < NULL_TOL),
        falsifier_desc="emergent B flux threads the axis — converged states only (E8)",
        falsifier=lambda r, c: (None if not c.get("converged")
                                else _num(r, "B_z_max_midplane") > NULL_TOL),
    ),
    # ---- Layer 5: soliton-level binding ----
    "binding_probe": DeviceContract(
        layer=5, layer_name="L5 soliton",
        calib_fixture="vacuum",
        calib_desc="A=0 → sector separation and Kähler ratio ≡ 0",
        calib_check=lambda r: (abs(_num(r, "sep_d_mean", 1.0)) < NULL_TOL
                               and abs(_num(r, "R_kahler", 1.0)) < NULL_TOL),
        falsifier_desc="Δu_∥ < 0 and |Δu_∥| ≫ noise floor — converged states only (E10)",
        falsifier=lambda r, c: (None if not c.get("converged")
                                else (r.get("du_par_sign") == -1
                                      and abs(_num(r, "du_par_extremum")) > BINDING_NOISE)),
    ),
}


# ---------------------------------------------------------------------------
# Vacuum fixture
# ---------------------------------------------------------------------------


def build_vacuum_world(ref: np.ndarray, n_slices: int, r_t: float) -> np.ndarray:
    """The ``A=0`` calibration fixture: reference lattice + the prestressed N-gon.

    Every node sits at its reference position on every slice, with only the
    per-slice global N-gon offset (the prestressed-vacuum background) added to the
    carrier 2-plane.  This is exactly the seed with ``A0=0`` — the state on which
    every device MUST read null after subtracting the offset.
    """
    n_nodes, m_ambient = ref.shape
    world = np.broadcast_to(ref, (n_slices + 1, n_nodes, m_ambient)).copy()
    off_re, off_im = vacuum_offsets(n_slices, r_t)
    world[:, :, CARRIER_RE] += off_re[:, np.newaxis]
    world[:, :, CARRIER_IM] += off_im[:, np.newaxis]
    return world


# ---------------------------------------------------------------------------
# Ledger assembly
# ---------------------------------------------------------------------------

_STATUS_FROM_BOOL = {True: "PASS", False: "FAIL", None: "untested"}


def build_ledger(
    results: dict[str, dict],
    calib_results: dict[str, dict],
    ctx: dict[str, Any],
) -> tuple[list[dict[str, Any]], int | None]:
    """Assemble ledger rows and the first failing emergence layer.

    Parameters
    ----------
    results : dict
        device name -> metric dict, measured on the actual run state.
    calib_results : dict
        device name -> metric dict, measured on the vacuum fixture (only for
        devices with ``calib_fixture == "vacuum"``).
    ctx : dict
        ``converged``, ``m``, ``n_t``, ``state``.

    Returns
    -------
    rows : list of dict (sorted by layer) with keys
        device, layer, layer_name, calib, falsifier, interpretable,
        calib_desc, falsifier_desc.
    first_fail_layer : int or None
        Lowest layer with any FAIL (calibration or falsifier); None if none fail.
    """
    rows: list[dict[str, Any]] = []
    for name, c in CONTRACTS.items():
        res = results.get(name, {})
        errored = "error" in res

        # --- calibration status ---
        if c.calib_fixture == "none":
            calib = "—"
        else:
            cres = calib_results.get(name)
            if cres is None or "error" in cres or c.calib_check is None:
                calib = "ERROR"
            else:
                try:
                    calib = "PASS" if c.calib_check(cres) else "FAIL"
                except Exception:
                    calib = "ERROR"

        # --- falsifier status ---
        if errored:
            falsifier = "ERROR"
        else:
            try:
                falsifier = _STATUS_FROM_BOOL.get(c.falsifier(res, ctx), "?")
            except Exception:
                falsifier = "ERROR"

        rows.append({
            "device": name,
            "layer": c.layer,
            "layer_name": c.layer_name,
            "calib": calib,
            "falsifier": falsifier,
            "calib_desc": c.calib_desc,
            "falsifier_desc": c.falsifier_desc,
        })

    fail_layers = [r["layer"] for r in rows
                   if r["calib"] == "FAIL" or r["falsifier"] == "FAIL"]
    first_fail = min(fail_layers) if fail_layers else None

    for r in rows:
        r["interpretable"] = first_fail is None or r["layer"] <= first_fail

    rows.sort(key=lambda r: (r["layer"], r["device"]))
    return rows, first_fail


def render_ledger_md(
    rows: list[dict[str, Any]],
    first_fail: int | None,
    ctx: dict[str, Any],
) -> str:
    """Render the trust ledger as the top section of report.md."""
    state = ctx.get("state", "?")
    verdict = (f"All instrumented layers interpretable (no calibration/falsifier "
               f"failure)."
               if first_fail is None else
               f"**First failing layer: L{first_fail}.** Devices above L{first_fail} "
               f"rest on a failed lower layer and are marked uninterpretable (⊘) — "
               f"fix the first ✗ before reading them.")

    lines = [
        "## Trust Ledger",
        "",
        f"State measured: **{state}**.  {verdict}",
        "",
        "| Layer | Device | Calibration (A=0 null) | Falsifier (pre-registered) | Verdict |",
        "|-------|--------|------------------------|----------------------------|---------|",
    ]
    sym = {"PASS": "✓ PASS", "FAIL": "✗ FAIL", "untested": "· untested",
           "ERROR": "! ERROR", "—": "— n/a", "?": "?"}
    for r in rows:
        if not r["interpretable"]:
            verdict_cell = "⊘ uninterpretable"
        elif r["falsifier"] == "FAIL" or r["calib"] == "FAIL":
            verdict_cell = "✗ FAIL"
        elif r["calib"] == "ERROR" or r["falsifier"] == "ERROR":
            verdict_cell = "! ERROR"
        elif r["falsifier"] == "PASS":
            verdict_cell = "✓ PASS"
        else:
            verdict_cell = "· provisional"
        lines.append(
            f"| L{r['layer']} {r['layer_name'].split(' ',1)[1] if ' ' in r['layer_name'] else ''} "
            f"| `{r['device']}` "
            f"| {sym.get(r['calib'], r['calib'])} — {r['calib_desc']} "
            f"| {sym.get(r['falsifier'], r['falsifier'])} — {r['falsifier_desc']} "
            f"| {verdict_cell} |"
        )
    lines += [
        "",
        "*Legend:* calibration runs each device on the vacuum (`A=0`) fixture in "
        "this same run and checks it reads null; the falsifier is the pre-registered "
        "pass criterion (in `branesim/diagnostics/contracts.py`). `untested` = a "
        "physics check only meaningful on a converged solved state. `⊘` = the layer "
        "below failed, so this verdict cannot be trusted yet.",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)